Module7 task1
htmlacademy-ecmascript/1662293-big-trip-15 pull request #11
Opened 2021-09-25 13:45 UTC by renatkm

Есть ошибка с дублированием панели сортировки после каждого клика на сортировку

Не реализовано добавление новых точек

2021-09-25 19:03 UTC, alexrusyn requested changes
Пересмотрите несколько рекомендаций.
В целом хорошая работа. Спасибо.

2021-09-25 19:03 UTC, alexrusyn commented on src/presenter/route.js
>      this._currentSortType = SortTypes.DAY.name;
Уже упоминалось - стоит сохранять тип сортировки как есть - объект полностью.

2021-09-25 23:54 UTC, renatkm commented on src/presenter/route.js
>      this._currentSortType = SortTypes.DAY.name;
Все так же не понимаю, зачем на данном этапе сохранять весь объект, если мы используем только одно его свойство?

2021-09-26 08:48 UTC, alexrusyn requested changes
Хорошо движемся! Но все еще есть недочеты.

2021-09-26 08:48 UTC, alexrusyn commented on src/presenter/point-new.js
> +export default class PointNew {
Пересмотрите визуальные [ошибки](https://take.ms/u6028)

2021-09-26 08:48 UTC, alexrusyn commented on src/utils/form-validation.js
> +const destinationValidation = (evt) => {
Валидация работает, но[ не совсем правильно](https://take.ms/aNwZE)

2021-09-26 08:48 UTC, alexrusyn commented on src/utils/render.js
> +  if (!component) {
В каком месте без дополнительной проверки данная функция не работает?

Если посмотреть то второе условие [справляется](https://take.ms/pkvsJ)
`null instanceof Abstract === false`
`undefined instanceof Abstract === false`

2021-09-26 08:48 UTC, alexrusyn commented on src/view/point-edit.js
> +    this.setFormSubmitHandler(this._callback.formSubmit);
в методе `reset` дублировать подписку на события не нужно

2021-09-26 15:03 UTC, alexrusyn approved these changes
Спасибо!

2021-09-26 15:03 UTC, merged