Module7 task2
htmlacademy-ecmascript/1662293-big-trip-15 pull request #14
Opened 2021-09-29 16:25 UTC by renatkm

2021-09-29 19:47 UTC, alexrusyn requested changes
Пересмотрите рекомендации - указаны некоторые в рамках подготовки к защите. У вас неплохо написанный код - давайте улучшим его и успешно защитим проект!

2021-09-29 19:47 UTC, alexrusyn commented on src/view/stats.js
> +    this._renderMoneyChart = moneyChart(moneyCtx, this._points);
В данной переменной хранится не рендер функция графиков, а экземпляр (instance)

2021-09-29 19:47 UTC, alexrusyn commented on src/view/stats.js
> +    if (this._callback._renderMoneyChart !== null || this._renderTypeChart !== null || this._renderTimeChart !== null) {
Что делает проверка?
Давайте подискутируем - дайте определение зачем вы ее используете.

2021-09-29 19:47 UTC, alexrusyn commented on src/view/stats.js
> +};
Форматирование.

2021-09-29 19:47 UTC, alexrusyn commented on src/utils/common.js
> +export const getHumanizedDiffTime = (datetime1, datetime2) => getDurationTime(dayjs(datetime1).diff(dayjs(datetime2)));
`datetime1, datetime2 -> dateA, dateB`

2021-09-29 19:47 UTC, alexrusyn commented on src/utils/common.js
>  import dayjs from 'dayjs';
В рамках защиты:
пересмотрите файлы `utils/common.js` и `utils/point.js` - много пересечений вспомогательных функций, а так же лишних функций.

2021-09-29 19:47 UTC, alexrusyn commented on src/view/stats.js
> +};
Визуальный [баг](https://take.ms/laGBW)

2021-09-29 19:47 UTC, alexrusyn commented on src/view/site-menu.js
> +    this._callback.menuClick(evt.target.text);
Передавайте не контент элемента, а сам элемент на который пользователь нажал.

2021-09-29 19:47 UTC, alexrusyn commented on src/view/site-menu.js
> +    });
Измените алгоритм:
- убираем активный класс для всех элементов меню
- добавляем активный класс к элементу на который пользователь нажал

2021-09-29 19:47 UTC, alexrusyn commented on src/main.js
> +const handleSiteMenuClick = (menuItem) => {
Вынесите общее из оператора переключения.

2021-09-29 19:47 UTC, alexrusyn commented on src/main.js
> +      document.querySelectorAll('.trip-filters__filter-input').forEach((filter) => filter.disabled = true);
Вынесите логику в соответствующие файлы, организуйте двухстороннее связывание.

<details>
  <summary>Подсказка</summary>
  `filter presenter` - логика
  `filter view`  - состояние
</details>

2021-09-29 19:47 UTC, alexrusyn commented on src/view/stats.js
> +  const types = points.map((point) => point.type);
Вынесите общее подготовительные функции.
Например - тип точки меняться?

`const types = points.map((point) => point.type);`

2021-09-29 19:47 UTC, alexrusyn commented on src/view/stats.js
> +  const sortedMoney = moneyArray.sort((a, b) => b[1] - a[1]);
Не нашел в техзадании необходимость сортировки.

2021-09-29 19:47 UTC, alexrusyn commented on src/view/stats.js
> +  return new Chart(moneyCtx, {
Вынесите общие стилевые настройки в объект конфигурации и изменяйте только то что необходимо конкретному графику. Используйте удобный способ копирования (стоит помнить о глубоком копировании - в данном случае избегайте его)

2021-09-30 07:08 UTC, alexrusyn requested changes
Еще немного нужно... Пересмотрите новые комментарии.

2021-09-30 07:08 UTC, alexrusyn commented on src/view/stats.js
> +  const moneyArray =  Array.from(points.reduce((point, { type, basePrice }) => point.set(type, (point.get(type) || 0) + basePrice), new Map));
Сложно читаемые функции - лучше разверните их.

```JS
const moneyArray = Array.from(
  points.reduce((point, { type, basePrice }) => {
    const accumulateBasePrice = point.get(type) || 0;
    return point.set(type, accumulateBasePrice + basePrice);
  }, new Map)
);
```

2021-09-30 07:08 UTC, alexrusyn commented on src/view/stats.js
> +  const canvasTypes = Object.values(CanvasType);
`canvasTypeList` - мы сменили тип данных и теперь это список (массив)

2021-09-30 08:53 UTC, alexrusyn approved these changes
Удачной защиты!

2021-09-30 08:54 UTC, renatkm commented on src/view/sorting.js
> +  const sortTypesList = Object.values(SortType);
to sortTypes (без List)

2021-09-30 08:54 UTC, merged