Шаблонизируй это
htmlacademy-ecmascript/1662293-big-trip-15 pull request #4
Opened 2021-09-12 23:04 UTC by renatkm

2021-09-13 20:43 UTC, alexrusyn requested changes
В целом неплохо, но есть еще над чем поработать 😄

2021-09-13 20:43 UTC, alexrusyn commented on src/view/point-edit.js
> +const createPointEditOfferTemplate = (offer, isChecked) => {
Рекомендация:

Объедините с `createPointEditOffersTemplate`, получится примерно так:

```
...
return (`
  <div class="event__available-offers">
    ${ offers.map((title, price) => (`
      <div class="event__offer-selector"></div>
    `)) }
  </div>
`);
```

2021-09-13 20:43 UTC, alexrusyn commented on src/view/point-edit.js
> +const createPointEditOfferTemplate = (offer, isChecked) => {
[Структура дополнительных опций ](https://take.ms/JXy3c) не несет в себе указатель активного состояния. По этому не стоит его, делать. 

2021-09-13 20:43 UTC, alexrusyn commented on src/view/point-edit.js
>        <section class="event__section  event__section--offers">
Внесите всю секцию в шаблон и добавьте логику вывода:
- если доп. опций нет
- если доп. опции есть

Пример можно найти в [демо проекте](https://github.com/htmlacademy-ecmascript/taskmanager-15/commit/d97a8af6fe4b3ad8533e013e302c1db684b9d0e5#diff-d3bdc89dfe9d96f5cb9a37b5081c02458c200ae96df959504dedc17313a3a254R28-R42)

2021-09-13 20:43 UTC, alexrusyn commented on src/view/point-edit.js
> +  return `<div class="event__offer-selector">
Выбор доп. опции так же [не работает](https://take.ms/kXKWg).

2021-09-13 20:43 UTC, alexrusyn commented on src/view/point-edit.js
> +                        <img class="event__photo" src="img/photos/2.jpg" alt="Event photo">
Не должно быть статических картинок

2021-09-13 20:43 UTC, alexrusyn commented on src/view/point-edit.js
>        <section class="event__section  event__section--destination">
Обработайте вариант отсутствия [данной секции](https://take.ms/S38zq). В соответствии с [версткой](https://take.ms/8SAe9).

2021-09-13 20:43 UTC, alexrusyn commented on src/view/point-edit.js
>        <div class="event__field-group  event__field-group--time">
Формат даты отличается от [шаблоного](https://take.ms/Qagrgj).

2021-09-14 11:25 UTC, renatkm commented on src/const.js
> +export const OfferList = [
стоит ли экспортную константу назвать по camelCase?

2021-09-14 11:40 UTC, alexrusyn commented on src/const.js
> +export const OfferList = [
Нет для задания констант используйте [такую форму записи](https://up.htmlacademy.ru/ecmascript/15/criteries#b5)

2021-09-14 18:12 UTC, renatkm reviewed
Finished my replies

2021-09-14 18:12 UTC, renatkm commented on src/view/point-edit.js
> +const createPointEditOfferTemplate = (offer, isChecked) => {
Не очень понятно замечание. 
У точки маршрута может быть набор выбранных опций, потому они стоят первым в статусе checked, далее после них показывается остальные опции доступные для выбора с учетом заданного типа события.
Поэтому я вынес создание темплейта для опции в отдельную функцию с передачей дополнительного параметра isChecked.

2021-09-14 18:12 UTC, renatkm commented on src/view/point-edit.js
> +const createPointEditPointTypesTemplate = (pointName) =>PointTypeList.map((pointType) => {
Так мне предлагает eslint :)

2021-09-14 18:12 UTC, renatkm commented on src/view/point-edit.js
>        <section class="event__section  event__section--destination">
Вывод текста "No avaliable offers"

2021-09-14 19:30 UTC, alexrusyn commented on src/view/point-edit.js
> +const createPointEditOfferTemplate = (offer, isChecked) => {
мы обсудили это в чате - https://take.ms/FZuAB
используйте предложенный подход - https://take.ms/gJ3SQ

2021-09-14 19:32 UTC, alexrusyn commented on src/mock/point.js
>    const {Destination, DepartureTime} = !prevPoint ?
Не вижу изменений, у вас есть вопрос по этому?

2021-09-14 20:17 UTC, alexrusyn requested changes
К сожалению все еще есть проблемы в некоторых местах. Если возникнут вопросы - буду рад ответить и помочь решить проблемы. Спасибо.

2021-09-14 20:17 UTC, alexrusyn commented on src/view/point-edit.js
>        <div class="event__field-group  event__field-group--time">
Не исправлено

2021-09-14 20:17 UTC, alexrusyn commented on src/view/point-edit.js
>        <section class="event__section  event__section--destination">
Следуйте [тех. заданию](https://up.htmlacademy.ru/ecmascript/15/project/big-trip#tripPointEdit).
Визуально выглядит [так](https://take.ms/keDMQn)

2021-09-14 20:17 UTC, alexrusyn commented on src/view/point.js
> +    <img class="event__type-icon" width="42" height="42" src="img/icons/${PointType}.png" alt="Event type icon">
В данном месте так же название картинки с маленькой буквы. Используйте принцип DRY.

2021-09-14 20:17 UTC, alexrusyn commented on src/view/point-edit.js
> +                        ${destinationPhotosTemplate}
Описание места назначения тоже может [отсутствовать ](https://take.ms/cMBVi)

2021-09-15 18:36 UTC, alexrusyn approved these changes
Хорошо двигаемся далее, только следите за форматированием документа.

2021-09-15 18:38 UTC, merged